export const getBranches = () => {

    return [

        "Biochemical Engineering",
        "Biochemical Engineering And Biotechnology",
        "Biotechnology",
        "Ceramic Engineering And Technology",
        "Ceramic Technology",
        "Chemical Engineering",
        "Chemical Engineering [Sf]",
        "Chemical Processing In Textiles",
        "Dairy Engineering",
        "Food Technology",
        "Food Technology And Management",
        "Leather Technology",
        "Metallurgical And Materials Engineering",
        "Metallurgical Engineering",
        "Perfumery And Flavour Technology",
        "Petrochem And Petroleum Refinery Engineering",
        "Petrochemical Engineering",
        "Petrochemical Technology",
        "Petroleum Engineering",
        "Polymer Technology",
        "Printing Technology",
        "Textile Design",
        "Textile Engineering",
        "Textile Manufacturing And Technology",
        "Textile Technology",
        "Wood Technology ",
        "Civil & Rural Engineering",
        "Civil Engineering",
        "Civil Environmental Engineering",
        "Civil Technology",
        "Construction Engineering",
        "Construction Engineerng And Management",
        "Drilling Engineering",
        "Drilling Technology",
        "Energy Engineering",
        "Energy Management",
        "Energy Science And Technology",
        "Environmental Engineering",
        "Environmental Science And Engineering",
        "Environmental Science And Technology",
        "Geomachines And Structures",
        "Geopraphic Information System (G.I.S.) & Global Positioning System",
        "Geotechnology ",
        "Green Technology",
        "Irrigation Engineering",
        "Mining & Mine Surveying",
        "Mining Engineering",
        "Product Engineering",
        "Product Design And Manufacturing",
        "Production Technology",
        "Structural Engineering",
        "Structural Engineering And Construction",
        "Traffic And Transporting Engineering",
        "Transportation Engineering",
        "Transportation Engineering And Management",
        "Transportation System Engineering",
        "Water And Environmental Technology",
        "Advanced Communication And Information System",
        "Advanced Computer Aided Design",
        "Advanced Design And Manufacturing",
        "Animation And Multimedia Technology",
        "Artificial Intelligence",
        "Bio Metrics & Cyber Security",
        "Bioinformatics",
        "Cad/Cam Engineering",
        "Communication And Information Systems",
        "Communication And Networking",
        "Communication Engineering",
        "Communication Engineering And Signal Processing",
        "Communications Engineering",
        "Computational Analysis In Mechanical Science",
        "Computational Mechanics",
        "Computer And Information Science",
        "Computer Application & Business Management",
        "Computer Applications",
        "Computer Engineering",
        "Computer Networking",
        "Computer Science & Engineering ",
        "Computer Science",
        "Cyber Security",
        "Data Sciences",
        "Digital Communication Engineering",
        "Embedded System And Vlsi Design",
        "Embedded Systems",
        "Information Science And Technology",
        "Information Technology",
        "Information Technology And Engineering",
        "Information Technology Enabled Services And Management",
        "Master Of Science In Software Engineering",
        "Multimedia Technology",
        "Nano Science & Technology",
        "Nano Technology ",
        "Network Engineering",
        "Printing Engineering",
        "Software Systems",
        "Spatial Information Technology",
        "System And Network Security",
        "System Management",
        "System Software",
        "Systems And Signal Processing",
        "Wireless Communication Technology",
        "Wireless Communications",
        "Wireless Networks And Applications",
        "Wireless Technology",
        "Electrical And Electronics Engineering",
        "Electrical And Instrumentation Engineering",
        "Electrical And Mechanical Engineering",
        "Electrical And Power Engineering",
        "Electrical Engineering",
        "Power Engineering",
        "Advanced Electronics And Communication Engineering",
        "Digital Systems",
        "Electronics & Communication Engg",
        "Electronics & Instrumentation Engineering ",
        "Electronics & Production",
        "Electronics & Telecommunication Engineering",
        "Electronics And Electrical Engineering",
        "Electronics And Instrumentation Engineering",
        "Electronics And Power Engineering",
        "Electronics Engineering",
        "Instrumentation & Control Engineering",
        "Instrumentation & Electronics",
        "Advanced Diploma In Marine Engineering And Systems",
        "Aero Space Engineering",
        "Aeronautical Engineering",
        "Agricultural Engineering",
        "Automobile Engineering",
        "Design Engineering",
        "Industrial And Production Engineering",
        "Marine Engineering",
        "Mechanical Engineering",
        "Mechatronics",
        "Nuclear Engineering",
        "Thermal Engineering",
        "Power Engineering",
    ]

};
