export const getDegrees = () => {

    return [
        "Bachelor of Architecture",
        "Bachelor of Arts",
        "Bachelor of Ayurvedic Medicine & Surgery",
        "Bachelor of Business Administration",
        "Bachelor of Commerce",
        "Bachelor of Computer Applications",
        "Bachelor of Dental Surgery",
        "Bachelor of Design",
        "Bachelor of Education",
        "Bachelor of Technology",
        "Bachelor of Engineering",
        "Bachelor of Fine Arts",
        "Bachelor of Fisheries Science",
        "Bachelor of Homoeopathic Medicine and Surgery",
        "Bachelor of Laws",
        "Bachelor of Library Science",
        "Bachelor of Mass Communications",
        "Bachelor of Medicine and Bachelor of Surgery",
        "Bachelor of Nursing",
        "Bachelor of Pharmacy",
        "Bachelor of Physical Education",
        "Bachelor of Physiotherapy",
        "Bachelor of Science",
        "Bachelor of Social Work",
        "Bachelor of Veterinary Science & Animal Husbandry",
        "Doctor of Medicine",
        "Doctor of Medicine in Homoeopathy - M.D. (Homoeopathy)",
        "Doctor of Pharmacy",
        "Doctor of Philosophy",
        "Doctorate of Medicine",
        "Master of Architecture",
        "Master of Arts",
        "Master of Business Administration",
        "Master of Chirurgiae",
        "Master of Commerce",
        "Master of Computer Applications",
        "Master of Dental Surgery",
        "Master of Design",
        "Master of Education",
        "Master of Technology",
        "Master of Engineering",
        "Master of Fine Arts",
        "Master of Laws",
        "Master of Library Science",
        "Master of Mass Communications/Media",
        "Master of Pharmacy",
        "Master of Philosophy",
        "Master of Physical Education",
        "Master of Physiotherapy",
        "Master of Science",
        "Master(of Arts) of Social Work",
        "Master of Science in Agriculture",
        "Master of Surgery",
        "Master of Veterinary Science"
    ]

};
