export const INCREMENT_LOADING = "TEST_INCREMENT_LOADING";
export const DECREMENT_LOADING = "TEST_DECREMENT_LOADING";
export const TEST_PUSH_DETAILS = "TEST_PUSH_DETAILS";
export const SECTION_PUSH_DETAILS = "SECTION_PUSH_DETAILS";
export const TEST_PUSH_ATTEMPTS = "TEST_PUSH_ATTEMPT";
export const QUESTION_PUSH_DETAILS = "QUESTION_PUSH_DETAILS";


export const CURR_SECTION_STATE = "CURR_SECTION_STATE";
