export const INCREMENT_LOADING = "TEST_INCREMENT_LOADING";
export const DECREMENT_LOADING = "TEST_DECREMENT_LOADING";
export const TEST_PUSH_DETAILS = "TEST_PUSH_DETAILS";
export const SECTION_PUSH_DETAILS = "SECTION_PUSH_DETAILS";
export const TEST_PUSH_ATTEMPTS = "TEST_PUSH_ATTEMPT";
export const QUESTION_PUSH_DETAILS = "QUESTION_PUSH_DETAILS";

// sections change
export const SECTION_UPDATE_CURRENT = "SECTION_UPDATE_CURRENT";

// questions
export const QUESTION_UPDATE_CURRENT = "QUESTION_UPDATE_CURRENT";

// test attempts
export const TEST_UPDATE_CHOICE_ATTEMPTS = "TEST_UPDATE_CHOCIE_ATTEMPT";
export const TEST_UNDO_CHOICE_ATTEMPTS = "TEST_UNDO_CHOICE_ATTEMPTS";


export const TEST_PUSH_ERROR = "TEST_PUSH_ERROR";
