const INCREMENT_LOADING = "TEST_INCREMENT_LOADING";
const DECREMENT_LOADING = "TEST_DECREMENT_LOADING";

const TEST_PUSH_DETAILS = "TEST_PUSH_DETAILS";
const SECTION_PUSH_DETAILS = "SECTION_PUSH_DETAILS";

const TEST_PUSH_ATTEMPTS = "TEST_PUSH_ATTEMPT";


export {INCREMENT_LOADING, DECREMENT_LOADING, TEST_PUSH_DETAILS, SECTION_PUSH_DETAILS, TEST_PUSH_ATTEMPTS};
